http:
  getListener:
    host: "localhost"
    port: "9071"
    path: "/flights"
  
  postListener:
    path: "/booking/flights"
    

db:
  getFlights:
    host: "flightsdb.cevzfi8xnzbk.ap-south-1.rds.amazonaws.com"
    port: "3306"
    user: "admin"
    password: "root12345"
    database: "FLIGHTS"